### ISSUE TITLE
不使用Docker该怎么运行这个项目

### ISSUE THREAD

**Issue by LanYangYang-114** [SerinaNya/SkinRenderMC#6]
操作系统是Windows，所以没法用Docker来部署项目，直接运行main.py则会出现一大串相对导入失败的报错（尝试了自己解决，但是没搞定）

**Comment by SerinaNya** [comment]
> 操作系统是Windows，所以没法用Docker来部署项目，直接运行main.py则会出现一大串相对导入失败的报错（尝试了自己解决，但是没搞定）

你说得很对，我设计的时候确实没有考虑到非 Docker 用户的处境。说实话我也并不希望你不在容器化平台上运行，很复杂。

尤其是这个 _browserless_，必须使用 Docker 来运行，没有任何能支持 Windows 平台的版本。当然你可以自己研究一下如何用普通的 Chrome 代替，但这需要修改代码。

**你可以使用 Docker Desktop 凑合一下，这玩意是可以在 Windows 上运行的。**
